### ISSUE TITLE
bringToBack and bringToFront not working 

### ISSUE THREAD

**Issue by AgentJay** [ptv-logistics/Leaflet.NonTiledLayer#16]
I get the error -

`Cannot read property 'insertBefore' of undefined` (line 107 of L.nonTiledLayer.js)

It appears that 'this._pane' is undefined and the functions is trying to add the layer to the beginning (or end) of the undefined array of layers.

I've been looking to try and find what I could use instead of this._pane but have found nothing so far. Please let me know if you can point me in the right direction. 

Cheers.

**Comment by AgentJay** [comment]
I had success by replacing the references to 'this._pane' with 'this._map._mapPane.childNodes[0]'

so line 107 becomes - 
`this._map._mapPane.childNodes[0].insertBefore(this._div, this._map._mapPane.childNodes[0].firstChild);`

Not sure if it's the best approach, but it works for me.

**Comment by r1m** [comment]
```this._pane``` seems to have been removed in leaflet 1.0.
Should replace it with ```this.getPane().insertBefore(...)```

**Comment by Marcoschmitt** [comment]
thx r1m. Change _pane to getPane() is working fine for Leaflet 1.0
