### ISSUE TITLE
Vaadin Plugin

### ISSUE THREAD

**Issue by giulianob83** [ptv-logistics/Leaflet.NonTiledLayer#19]
I'm using your plugin for create a v-leaftlet plugin.When i add nontiledlayer i receive this error message:

this.callInitHooks is not a functioncom.google.gwt.core.client.JavaScriptException: (TypeError) : this.callInitHooks is not a function

**Comment by oliverheilig** [comment]
Hi,

are you sure the layer is instantiated correctl? Looks like the error mentioned here https://github.com/Leaflet/Leaflet/issues/3736. Either cretate the layer with new 

        var layer= new L.NonTiledLayer.WMS(xMapWmsUrl, {

or better use the factory method

        var layer = L.nonTiledLayer.wms(xMapWmsUrl, {

Oliver

**Comment by giulianob83** [comment]
Thanks Oliver, resolved!

**Comment by oliverheilig** [comment]
You're welcome!
