### ISSUE TITLE
WMS goes to upper left corner when zooming in 

### ISSUE THREAD

**Issue by pmikla14** [ptv-logistics/Leaflet.NonTiledLayer#20]
Hi! 

Thank you for the plugin, great thing!
Tiles are loaded correct and very fast, there is only one problem with my WMS Layer: when I zoom in, the layer(image) is not getting bigger, so the layer seems to move to the upper left corner of the map.

Here you can see what I mean: https://www.gis4event.at/stveit/

This is my code, what am I doing wrong? 

 ```
map = L.map('map', {
		worldCopyJump: true,
		zoomSnap: 0.25,
		zoomDelta: 0.5,
		wheelPxPerZoomLevel: 50,
		bounceAtZoomLimits: false,
        fadeAnimation: true,
        inertia: true,
        crs: crs3857,
        maxBounds: maxArea,
        minZoom: 16,
		maxZoom: 20
    });

...

layer = new L.NonTiledLayer.WMS("https://www.gis4event.at/...", {
            layers: "layername",
            format: "image/png",
            transparent: true,
	    maxZoom: 25,
            crs: L.CRS.EPSG4326
        }).addTo(map);
```

**Comment by oliverheilig** [comment]
Hello,

I've looked at your application. It works well for me, but it looks like you're not using the latest version. There's a new package that contains both NonTiledLayer and NonTiledLayer.WMS and it works both for LL 0.7.x. and 1.0.x

npm: https://www.npmjs.com/package/leaflet.nontiledlayer 
unpkg: https://unpkg.com/leaflet.nontiledlayer

or just include

https://unpkg.com/leaflet.nontiledlayer@1.0.3/dist/NonTiledLayer.js

Oliver

**Comment by pmikla14** [comment]
Hi!

Thank you for the fast answer! I’ve updated the file, but still having the same troubles… 
Is this normal? http://screencast-o-matic.com/watch/cbeYFN6CpY <http://screencast-o-matic.com/watch/cbeYFN6CpY>

Thanks,
Philipp

**Comment by oliverheilig** [comment]
Hi Philipp,

strange, it works in a standalone window. It looks like Leaflet has problem with the _latLngBoundsToNewLayerBounds function when running in this container. Can you reproduce it standalone or can you test it with the standard Leaflet ImageOverlay?

**Comment by pmikla14** [comment]
Hi Oliver!

I made a test-file only with leaflet and your plugin, still having the same troubles: https://www.gis4event.at/stveit/test.html

I dont really know what you are doing different in your demo… I also tried to change the leaflet version to 1.0.2, like in the demo, but nothing changed…

Thank you!
Philipp

**Comment by oliverheilig** [comment]
Looks to me like you're not using the right css for Leaflet 1.0.3. If i inclde the correct 1.0.3 .js and .css if works.

```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
```

**Comment by pmikla14** [comment]
Thank you very very much, what a dumb mistake! It’s working now :-)

Philipp

**Comment by oliverheilig** [comment]
No problem. If we meet some day you can buy me a beer :)
