### ISSUE TITLE
Replace L.Mixin.Events with L.Evented

### ISSUE THREAD

**Issue by dbauszus-glx** [ptv-logistics/Leaflet.NonTiledLayer#21]
L.Mixin.Events is deprecated and will be removed in future Leaflet builds.

There is one occurance of L.Mixin.Events in [src/NonTiledLayer.js](https://github.com/ptv-logistics/Leaflet.NonTiledLayer/search?utf8=%E2%9C%93&q=mixin&type=) which causes a warning when I use the library with the current (1.2.0) Leaflet version.

```
var L = require('leaflet');
L.NonTiledLayer = (L.Layer \|\| L.Class).extend({
  includes: L.Mixin.Events,

```
I replace L.Mixin.Events with L.Evented.prototype as suggested by @IvanSanchez in this [case](https://github.com/Leaflet/Leaflet/issues/5358). However, I am not sure whether this might break compatibility with older Leaflet versions.

ps. I absolutely love your plugin. Been using this for years with pretty much every Leaflet map I make.

**Comment by oliverheilig** [comment]
Yes, i know the warning messages are annoying. I'll check how to remove it while maintainig compatibility.

**Comment by dbauszus-glx** [comment]
```
L.NonTiledLayer = (L.Layer || L.Class).extend({
  includes: L.Evented.prototype || L.Mixin.Events,
```

This should be fairly save to use.

**Comment by oliverheilig** [comment]
I think 

`includes: L.Evented || L.Mixin.Events,`

did it, check 

https://unpkg.com/leaflet.nontiledlayer@1.0.6/dist/
