### ISSUE TITLE
Support the 'loading' event

### ISSUE THREAD

**Issue by cosme-benito** [ptv-logistics/Leaflet.NonTiledLayer#22]
Since the 'load' event (triggered when all tiles finish loading) is supported, it would make sense to also support the 'loading' event (triggered when a tile starts loading). 

I assume the implementation is very easy. As a workaround I simply added

`this.fire('loading');`

to the _update function, though I'm not sure that is the correct approach.

**Comment by oliverheilig** [comment]
I put it right before setting the url.
