### ISSUE TITLE
GetFeatureInfo

### ISSUE THREAD

**Issue by iByteDev** [ptv-logistics/Leaflet.NonTiledLayer#27]
This plugin has support for getfeatureinfo?

**Comment by oliverheilig** [comment]
L.NonTiledLayer.WMS is equivalent to L.TileLayer.WMS and only supports WMS/GetMap requests. Any other requests (getfeatureinfo, getcapabilities) have to be implemented outside the layer.

**Comment by iByteDev** [comment]
thanks for your answer.
Could you guide me how to do it?

**Comment by oliverheilig** [comment]
fyi, there are dedicated WMS plugins which implement these features.

https://github.com/heigeo/leaflet.wms
