### ISSUE TITLE
Pane option

### ISSUE THREAD

**Issue by kitzilla** [ptv-logistics/Leaflet.NonTiledLayer#4]
Thank you for your suggestion on the other thread (https://github.com/Leaflet/Leaflet/issues/558). Eventually, I came back to NonTiledLayer.

In my app, the L.Map instance and layer instances are instantiated asynchronously (ie NonTiledLayer could be generated before the map is instantiated), so I modified the default pane to tilePane to get around this. 

I wonder if the pane option allows some predefined strings (eg. 'tilePane', 'markerPane') as well as pane instances, it will be useful in such circumstances.

Or perhaps a simple 'addAsOverlay' (true = overlayPane / false = tilePane) option would be sufficient because nobody will want to add WMS to the other panes.

**Comment by oliverheilig** [comment]
There's a pane option at the Layer base class in Leaflet 1.0. I've changed it to this mechanism. Look at the sample where the label layer is inserted at the tile pane.
