### ISSUE TITLE
Version control (npm)

### ISSUE THREAD

**Issue by r1m** [ptv-logistics/Leaflet.NonTiledLayer#7]
I would be nice to have a package.json with actual version that follows semantic versionning.
And git tags that matches release versions.
It allows a better control on dependencies with npm.

**Comment by oliverheilig** [comment]
Yes, you are right. It would be helpful to make it conform to the official plugin authoring guide

https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md

I will read it

**Comment by nmco** [comment]
Any news on this ? If I understood correctly the current published version in npm is compatible with leaflet master, any change that this release https://github.com/ptv-logistics/Leaflet.NonTiledLayer/releases/tag/v0.7.3 gets also published in npm ? Thanks for this module :)

**Comment by oliverheilig** [comment]
Hi,

didn't find the time to deal with npm publishing yet. Hope i can find the time to add npm publishing next week.

Oliver

**Comment by nmco** [comment]
Very good news thank you :)

**Comment by oliverheilig** [comment]
Hi,

i did a test publishing a while ago

https://www.npmjs.com/package/leaflet.nontiledlayer

Now i wanted to test it with this tutorial

http://makerlog.org/posts/leaflet-basics

But browserify/require don't work when just publishing it, at least with Leaflet 1.0. Afaik i need to implement an APM, like explained here 

https://github.com/Leaflet/Leaflet/issues/2783

So making it an "official" plugin is still some work.

**Comment by oliverheilig** [comment]
Ok, 

https://www.npmjs.com/package/leaflet.nontiledlayer
