### ISSUE TITLE
Default pane invalid

### ISSUE THREAD

**Issue by ram-one** [ptv-logistics/Leaflet.NonTiledLayer#8]
I was wondering if NonTiledLayer should not be added to the ```tilePane``` of the map instead of the default one ```overlayPane```.
Sure I can change it with ```pane``` option.
But I believe theses layers should not belong to overlay by default.

**Comment by oliverheilig** [comment]
It depends on the use-case. If you use the non-tiled layer for basemap-content, tile tilePane is the better option (like the L.TileLayer). If you use it for overlay-content, the overlay pane (like for the L.ImageOverlay layer). Sure i we could this, but this would be a breaking change. Any other opinions?

**Comment by ram-one** [comment]
I guess, this is pure personal opinion.
I used this mostly for weather maps, so they belong to the tilePane and I was asking myself "why are they in overlay ?"

But then I saw that you use it for overlay icons, so that makes sense.
It's not a blocking issue since we can easily change it.
